name: GitHub Actions Demo
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check commit message
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/checkLatestCommit.sh "${{ github.event.head_commit.message }}"
